name: Deploy Lumen API to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 4: Deploy to DigitalOcean
    - name: Deploy to Droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /var/www/api1.tufaan.xyz  # Navigate to your project directory
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate
          php artisan cache:clear
        EOF
